preset: symfony

enabled:
    - ordered_use
    - strict

disabled:
    - empty_return
    - phpdoc_annotation_without_dot # This is still buggy: https://github.com/symfony/symfony/pull/19198

    # Puli is using a reserved keyword as a class
    # (Puli\Repository\Api\Resource\Resource)
    # https://github.com/puli/issues/issues/119
    - phpdoc_types
